dataset:
  image_dir: "dataset/images"
  annotation_file: "dataset/annotations/instances.json"
  mask_dir: "dataset/masks"
  
training:
  batch_size: 4
  epochs: 20
  learning_rate: 0.0001
  model_save_path: "models/sidewalk_detector.pth"
